### ISSUE TITLE
KeyError: Statistics

### ISSUE THREAD

**Issue by IlGnome** [edwardslabs/CloudBot#111]
The youtube API seems to no longer (at least not currently) supplying the statistics information. 
My dirty fix is to comment    https://github.com/edwardslabs/CloudBot/blob/gonzobot/plugins/youtube.py#L33 and `add statistics = ''`

**Comment by linuxdaemon** [comment]
Can you include logs and perhaps the json object returned by the API? I'm unable to replicate, on my test instance, the API always includes the `statistics` object.

**Comment by IlGnome** [comment]
Issue seems to have fixed itself.
