### ISSUE TITLE
ipv6

### ISSUE THREAD

**Issue by shellie03** [edwardslabs/CloudBot#117]
Could you add ipv6 to the connection section please?

**Comment by edwardslabs** [comment]
I am not sure I understand your question.

**Comment by shellie03** [comment]
I'm sorry I wasn't real clear. In the configuration file where you put the IRC server to connect to and if you want ssl. Can we put an ipv6 option?

**Comment by edwardslabs** [comment]
have you tried specifying an ipv6 address or dns record?

**Comment by shellie03** [comment]
I have an ipv6 address that resolves in dns record correctly. I can connect manually using the ipv6 address but I have to give the irc client the "-6" command to force it to use ipv6 and not resort to ipv4.

**Comment by edwardslabs** [comment]
I am not sure if this will work but try adding "bind_addr":your ipv6 address to see if it force the use of ipv6.

https://github.com/edwardslabs/CloudBot/blob/gonzobot/cloudbot/bot.py#L144-L150 is the only reference I can find to specifying which interface to bind to.

**Comment by shellie03** [comment]
Thank you!
