### ISSUE TITLE
pyeval no longer works due to API deprecation

### ISSUE THREAD

**Issue by leonthemisfit** [edwardslabs/CloudBot#141]
Google appengine's Python 2.5 service has reached end of life and has been fully shutdown. Because of this the gonzobot .python command is no longer functioning. More information can be found here: https://cloud.google.com/appengine/docs/deprecations/

**Comment by starsparrow** [comment]
Just found this out independently. More info:

`$ curl pyeval.appspot.com` returns the following after the transfer information:
>Python 2.5 is no longer available.  Please refer to https://goo.gl/aESk5L for more information.

(The goo.gl shortlink resolves to the one that @leonthemisfit posted above)
