### ISSUE TITLE
BTC output 

### ISSUE THREAD

**Issue by dameware99** [edwardslabs/CloudBot#186]
This seems to be one of the first things people levitate towards when going through the command list. Would love to not see the error messages.

**Comment by linuxdaemon** [comment]
The issue seems to be that the site itself is messed up. https://coinmarketcap-nexuist.rhcloud.com/ is returning that the root of the site can not be found. Unless this service is fixed or another API can replace it, I'm afraid this command may no longer work.

**Comment by edwardslabs** [comment]
someone pm'd me today on snoonet and said they had coded a replacement. Hopefully they put in a PR.
