### ISSUE TITLE
Feature request Last.fm: Track tags

### ISSUE THREAD

**Issue by KataStrofY** [edwardslabs/CloudBot#68]
Since Last.fm also allows tagging on Tracks/Songs, it would be better to try grabbing those before Artists tags, as they are more likely to be correct in these situations:
1) An artist or band makes music in different genres. Artist tag might not show the corresponding genre to current played track.
2) An artist or band name that is shared between 2 or more bands.

Example 1: 
Minamotoya - Stardust [Trance]
Minamotoya - Momiji Hunting [Happy Hardcore]

Example 2:
Interstate (Persons in this group: Lars Döller, Ralf Merlé) - Human Beings [Hard Trance]
Interstate (Person in this group: Scott Brown) - Forever Yours [Happy Hardcore]

**Comment by edwardslabs** [comment]
@typoguy if you want to look at this be my guest.
